name: run-if-diff
description: Run a command if files are different
inputs:
  cwd:
    description: The directory containing the .git directory
    required: false
    default: .
  since:
    description: The git ref to compare the current working directory to
    required: false
  file-path:
    description: The file paths (or glob) to filter the files by
    required: false
  file-status:
    description: The file statuses to filter the files by
    required: false
outputs:
  ref:
    description: The git ref
  count:
    description: The number of files that have changed and match the filter
  paths:
    description: The paths of files that have changed and match the filter
runs:
  using: "node12"
  main: "lib/action/index.js"
