name: Action

on:
  push:
    branches: master
  pull_request:

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth 1 origin refs/tags/previous:refs/tags/previous

      - id: run-if-diff
        uses: jameslnewell/run-if-diff@master
        with:
          since: previous

      - name: Get the ref
        run: 'echo "ref: ${{ steps.run-if-diff.outputs.ref }}"'

      - name: Get the file count
        run: 'echo "count: ${{ steps.run-if-diff.outputs.count }}"'

      - name: Get the file paths
        run: 'echo -e "paths: \n${{ steps.run-if-diff.outputs.paths }}"'

      - name: Conditional command
        if: ${{ steps.run-if-diff.outputs.count > 0 }}
        run: echo "Expensive command..."

      - run: |
          git config --global user.name 'James Newell'
          git config --global user.email 'jameslnewell@users.noreply.github.com'
          git tag --force previous
          git push --tags --force
