name: Action

on:
  push:
    branches: master
  pull_request:

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin 3.0.0
      - id: run-if-diff
        uses: jameslnewell/run-if-diff@master
        with:
          since: 3.0.0
      - name: Get the ref
        run: echo "ref=${{ steps.run-if-diff.outputs.ref }}"
      - name: Get the files
        run: echo "files=${{ steps.run-if-diff.outputs.files }}"
